### ISSUE TITLE
Erro callcenter - ligação sendo atendida e não mostrando no console o status 

### ISSUE THREAD

**Issue by johnnyvaz** [ibinetwork/IssabelBR#6]
ola, estou com um problema no módulo callcenter, quando a ligação cai para o atendente, não está mudando o status no agente do console,
minhas configurações:

![image](https://user-images.githubusercontent.com/18165255/50913696-09f1eb80-141c-11e9-8bec-4af07d1be6fa.png)

![image](https://user-images.githubusercontent.com/18165255/50913861-7a990800-141c-11e9-974a-4fbbb81fcf4d.png)

![image](https://user-images.githubusercontent.com/18165255/50913940-a7e5b600-141c-11e9-806e-0d7f94509ef1.png)

**Comment by rxsantos** [comment]
Boa tarde Johny,

Sugiro parar e reiniciar o discador em “Configurações”.

 

Att,

Roberto Xavier

 

De: Johnny Vaz [mailto:notifications@github.com] 
Enviada em: quarta-feira, 9 de janeiro de 2019 15:08
Para: ibinetwork/IssabelBR <IssabelBR@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [ibinetwork/IssabelBR] Erro callcenter - ligação sendo atendida e não mostrando no console o status (#6)

 

ola, estou com um problema no módulo callcenter, quando a ligação cai para o atendente, não está mudando o status no agente do console,
minhas configurações:

 <https://user-images.githubusercontent.com/18165255/50913696-09f1eb80-141c-11e9-8bec-4af07d1be6fa.png> 

 <https://user-images.githubusercontent.com/18165255/50913861-7a990800-141c-11e9-974a-4fbbb81fcf4d.png> 

 <https://user-images.githubusercontent.com/18165255/50913940-a7e5b600-141c-11e9-806e-0d7f94509ef1.png>

**Comment by johnnyvaz** [comment]
Resolvi o problema alterando as configurações no sip_custom diretamente pela tela do freepbx, acredito que o problema era porque estava habilitado a ligação mesmo a linha estando ocupada, e desativando esta opção o sistema reconheceu e o callcenter está funcionando.

**Comment by ibinetwork** [comment]
Manda detalhes do que você modificou para que todos tenham acesso a 
informação, compartilha a solução com a comunidade!

Abraços


Em 10/01/2019 09:10, Johnny Vaz escreveu:
