### ISSUE TITLE
How can i install i have issabel already installed

### ISSUE THREAD

**Issue by Ma7m0d** [ibinetwork/IssabelBR#8]

**Comment by Ma7m0d** [comment]
?

**Comment by ibinetwork** [comment]
wget -O - https://github.com/ibinetwork/IssabelBR/raw/master/patch-issabelbr.sh | bash

**Comment by Ma7m0d** [comment]
> wget -O - https://github.com/ibinetwork/IssabelBR/raw/master/patch-issabelbr.sh | bash

thanx you
